global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "product-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["product:8081"]

  - job_name: "category-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["category:8082"]

  - job_name: "user-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["user:8083"]
